name: release-please
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Check secret
        run: |
          if [[ -z "${{ secrets.RELEASE_PLEASE_TOKEN }}" ]]; then
            echo "Secret is not available"
            exit 1
          else
            echo "Secret is available"
          fi
      - name: Run Release Please
        uses: google-github-actions/release-please-action@v4
        with:
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
          release-type: simple

  update-version:
    needs: release-please
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Update package.json version
        run: |
          VERSION=$(jq -r .version package.json)
          NEW_VERSION="${VERSION%.*}.$((${VERSION##*.}+1))"
          jq ".version=\"$NEW_VERSION\"" package.json > tmp.json && mv tmp.json package.json
      - name: Commit and push
        run: |
          git config --local user.email "daud.java@gmail.com"
          git config --local user.name "daudzubaidi"
          git commit -am "Bump version to $NEW_VERSION"
          git push