name: release-please

on:
  pull_request:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      branch: ${{ steps.release.outputs.branch }}
    steps:
      - name: Run Release Please
        id: release
        uses: google-github-actions/release-please-action@v4
        with:
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
          release-type: simple

  update-version:
    needs: release-please
    if: needs.release-please.outputs.branch != ''
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: ${{ github.ref }}
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Update package.json version
      run: |
        VERSION=$(jq -r .version package.json)
        MAJOR_MINOR_VERSION="${VERSION%.*}"
        PATCH_VERSION="${VERSION##*.}"
        NEW_PATCH_VERSION=$(($PATCH_VERSION+1))
        NEW_VERSION="$MAJOR_MINOR_VERSION.$NEW_PATCH_VERSION"
        jq ".version=\"$NEW_VERSION\"" package.json > tmp.json && mv tmp.json package.json
    - name: Commit and push
      run: |
        git config --local user.email "daud.java@gmail.com"
        git config --local user.name "daudzubaidi"
        BRANCH_NAME=${GITHUB_REF#refs/heads/}
        git checkout $BRANCH_NAME
        git diff --quiet && git diff --staged --quiet || (git commit -am "Bump version to $NEW_VERSION" && git push origin $BRANCH_NAME)