name: release-please
on:
  push:
    branches:
      - main
      - beta  # Assuming you have a beta branch for pre-releases

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v4

      - name: Determine if Pre-release
        id: prerelease_check
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/beta" ]]; then
            echo "IS_PRERELEASE=true" >> $GITHUB_ENV
          else
            echo "IS_PRERELEASE=false" >> $GITHUB_ENV
          fi

      - name: Run Release Please
        id: release
        uses: google-github-actions/release-please-action@v4
        with:
          release-type: node
          versioning-strategy: prerelease
          prerelease: ${{ env.IS_PRERELEASE }}

      - name: Get Data from PR Release Please
        id: get-pr-data
        run: |
          PR_TITLE=$(echo '${{ steps.release.outputs.pr }}' | jq -r '.title')
          PR_HEAD_BRANCH_NAME=$(echo '${{ steps.release.outputs.pr }}' | jq -r '.headBranchName')
          echo "PR_TITLE=$PR_TITLE" >> $GITHUB_ENV
          echo "PR_HEAD_BRANCH_NAME=$PR_HEAD_BRANCH_NAME" >> $GITHUB_ENV

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ env.PR_HEAD_BRANCH_NAME }}

      - name: Update package.json version
        run: |
          if [[ "$PR_TITLE" =~ .*release.* ]]; then
            VERSION=$(echo "$PR_TITLE" | grep -oE '([0-9]+\.[0-9]+\.[0-9]+(-[a-zA-Z0-9]+)?)')
            if [ -z "$VERSION" ]; then
              echo "No version found in PR title, trying to extract from last commit for simple release type."
              LAST_COMMIT_MSG=$(git log -1 --pretty=%B)
              VERSION=$(echo "$LAST_COMMIT_MSG" | grep -oE '([0-9]+\.[0-9]+\.[0-9]+(-[a-zA-Z0-9]+)?)')
            fi
            if [ ! -z "$VERSION" ]; then
              jq ".version=\"$VERSION\"" package.json > tmp.json && mv tmp.json package.json
              echo "Updated package.json to version $VERSION."
              echo "NEW_VERSION=$VERSION" >> $GITHUB_ENV
            else
              echo "No version found in PR title or last commit, skipping package.json update."
            fi
          else
            echo "PR title does not indicate a release, skipping package.json update."
          fi